# Generated by Django 4.2 on 2023-04-19 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_candidate', models.BooleanField(default=False)),
                ('is_substitute', models.BooleanField(default=False)),
                ('program', models.CharField(max_length=100)),
                ('votes_amount', models.IntegerField(default=0)),
                ('candidate_group', models.IntegerField(default=0)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profile_images/')),
                ('has_voted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
