# Generated by Django 4.2 on 2023-04-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_remove_userdetail_is_candidate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVotation',
        ),
    ]
