# Generated by Django 4.2 on 2023-04-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_delete_uservotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='is_substitute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='propossals',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='votes_received',
            field=models.IntegerField(default=0),
        ),
    ]
