# Generated by Django 4.2 on 2023-05-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0007_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="first_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
