# Generated by Django 4.2 on 2023-05-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0009_userprofile_active_userprofile_id_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id_user",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
