# Generated by Django 4.2 on 2023-05-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0010_alter_userprofile_id_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="private_key",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="public_key",
            field=models.TextField(),
        ),
    ]
