# Generated by Django 4.2 on 2023-05-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mempool_app", "0002_mempooltransaction_is_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="mempooltransaction",
            name="node_id",
            field=models.CharField(default="nodeidtodelete12345678", max_length=100),
        ),
        migrations.AddField(
            model_name="mempooltransaction",
            name="related_votation",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
