# Generated by Django 4.2 on 2023-05-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mempool_app", "0003_mempooltransaction_node_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mempooltransaction",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="mempooltransaction",
            name="vote",
        ),
        migrations.AddField(
            model_name="mempooltransaction",
            name="sender_signature",
            field=models.CharField(default="0", max_length=500),
        ),
        migrations.AddField(
            model_name="mempooltransaction",
            name="trx_data",
            field=models.CharField(default="0", max_length=500),
        ),
        migrations.AlterField(
            model_name="mempooltransaction",
            name="node_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mempooltransaction",
            name="sender",
            field=models.CharField(max_length=100),
        ),
    ]
