# Generated by Django 4.2 on 2023-04-17 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0003_remove_chain_block_remove_chain_validate_block_chain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
