# Generated by Django 4.2 on 2023-04-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_app', '0004_chain_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
