# Generated by Django 4.2 on 2023-05-07 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain_app", "0005_alter_chain_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="block",
            name="hash",
        ),
    ]
