# Generated by Django 4.2 on 2023-05-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blockchain_app", "0006_remove_block_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="vote",
        ),
        migrations.AddField(
            model_name="transaction",
            name="node_id",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender_signature",
            field=models.CharField(default="0", max_length=500),
        ),
        migrations.AddField(
            model_name="transaction",
            name="trx_data",
            field=models.CharField(default="0", max_length=500),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.CharField(max_length=100),
        ),
    ]
