# Generated by Django 4.2 on 2023-05-07 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.CharField(max_length=50)),
                ("net_address", models.CharField(max_length=250)),
                ("public_key", models.CharField(max_length=500)),
                ("private_key", models.CharField(max_length=500)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("processing_capacity", models.IntegerField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
