# Generated by Django 4.2 on 2023-05-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nodes_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="private_key",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="node",
            name="public_key",
            field=models.TextField(),
        ),
    ]
